screen:
  size: 300   #initial screen size
  percentage change: 50   #percentage of screen size variation
  margin: 20   #distance ratio between the adjacent and the screen edge   

star:
  opposite:   #the length of opposite is depended on adjacent 
    ratio to adjacent:   #the length of adjacent is depended on the screen size
      min: 0.3
      max: 0.7
  point:   #the number of points of a star
    min: 4
    max: 11
  starting angle:   #the starting rotating of the first point
    min: -90
    max: 90
  distance from center:  #distance ratio between the points and the center
    min: 0 
    max: 1

path: stars   #folder path to store the graphics